### ISSUE TITLE
Simulate constant load for period of time

### ISSUE THREAD

**Issue by pradykaushik** [pradykaushik/cpu-load-generator#10]
Currently, there is no support for simulating a constant CPU/Memory load for a set period of time.

It seems that step size can be set to 0 but this would result in an [infinite loop](https://github.com/pradykaushik/cpu-load-generator/blob/master/SimulateConstIncreaseCPULoad.java#L89).

We should support specifying that a constant load needs to be generated (`--constant-load` command line flag).

**Comment by bm1216** [comment]
Hey, any progress with this one? Thanks

**Comment by pradykaushik** [comment]
Hi @bm1216 I'm yet to start working on this. Thanks for showing interest towards the project.
I have been a little caught up with other things over the last few months and therefore haven't really had the chance to get this going.
I have some free time this week and the next one so I am going to work on this (unless you want to take it up yourself and contribute to the project :) ).

**Comment by pradykaushik** [comment]
@bm1216 you can follow #16 for this. I have a couple more changes that I'd like to push in before merging into master.

**Comment by pradykaushik** [comment]
#16 merged!

@bm1216 you should now be able to generate constant load. Please close this issue if everything works correctly. Open a new issue if things don't work as expected.

**Comment by pradykaushik** [comment]
closing this. If you have any issues with the constant CPU load generation, please open another issue.
